### ISSUE TITLE
Putting on CTAN?

### ISSUE THREAD

**Issue by rolfn** [csachs/luaimageembed#1]
Hello Christian,
what do think about putting your useful package to CTAN?

...Rolf

**Comment by csachs** [comment]
Hi Rolf,
thanks for your interest in the package!
Yes, I very much had this in mind, it just kinda shifted back on my TODO list …
I'll try to prepare this in the next days.

Best regards, Christian

**Comment by rolfn** [comment]
Good to hear. It would be nice to have "luaimageembed" in the upcoming "TeX Live 2019" distribution. There are only few days until the dead-line.

Thank you for the nice package!

...Rolf

**Comment by csachs** [comment]
It's supposed to show up within 24h.
